import createConfig from "../../rollup.config.js";

const inputs = [
  "app-bar",
  "autocomplete",
  "avatar",
  "badge",
  "bottom-sheet",
  "breadcrumb",
  "button",
  "button-group",
  "calendar",
  "card",
  "checkbox",
  "chips",
  "content-pane",
  "core",
  "date-input",
  "datepicker",
  "dialog",
  "divider",
  "drawer-container",
  "expansion-panel",
  "fab",
  "fab-menu",
  "form-field",
  "gestures",
  "heading",
  "icon",
  "icon-button",
  "list",
  "loading-indicator",
  "menu",
  "nav-bar",
  "nav-menu",
  "nav-rail",
  "option",
  "paginator",
  "progress-indicator",
  "radio-group",
  "search",
  "segmented-button",
  "select",
  "shape",
  "skeleton",
  "slide-group",
  "slider",
  "snackbar",
  "split-button",
  "split-pane",
  "stepper",
  "switch",
  "tabs",
  "textarea-autosize",
  "theme",
  "timepicker",
  "toc",
  "toolbar",
  "tooltip",
  "tree",
];

export default createConfig({
  inputs: inputs,
  externals: [/^@m3e\//, "lit", "@lit/react", "react"],
  allExternals: [/^@m3e\/web\//, "react"],
  config: {
    terserConfig: {
      compress: { directives: false },
    },
  },
});
